site_name: RedPlanet
repo_url: https://github.com/humboldt-penguin/redplanet
repo_name: RedPlanet
# site_url: TODO

theme:
  name: material

  palette:
    ## toggle dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    ## toggle light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  icon:
    logo: material/satellite-variant
    repo: fontawesome/brands/github

  features:
    - navigation.tabs  ## tabs in the top bar (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs )
    - content.code.copy  ## code blocks: copy button (https://squidfunk.github.io/mkdocs-material/reference/code-blocks/ )
    - navigation.instant  ## behaves like a single-page application, i.e. extremely fast for free (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading )
    - navigation.indexes  ## clicking on a section brings you to an overview page (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages )


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  ## see: https://mkdocstrings.github.io/python/usage/#using-the-paths-option
          options:
            docstring_style: numpy
            force_inspection: true  ## resolve dynamic docstrings, mainly from `@substitute_docstrings` decorator -- TODO: implement selective inspection at some point, see: https://mkdocstrings.github.io/griffe/guide/users/how-to/selectively-inspect/
            annotations_path: source  ## verbosity for annotations path, e.g. `ndarray` vs `numpy.ndarray` (see: https://mkdocstrings.github.io/python/usage/configuration/signatures/#annotations_path )
            # docstring_section_style: list  ## render parameters/returns/etc as bulleted lists (like numpy) instead of the default tables (see: https://mkdocstrings.github.io/python/usage/configuration/docstrings/?h=docstring_section_style#list )
            show_root_heading: true  ## make function titles visible on page (see: https://mkdocstrings.github.io/python/usage/configuration/headings/#show_root_heading )
            heading_level: 1
            separate_signature: true  ## put function signature in a code block below the heading (see: https://mkdocstrings.github.io/python/usage/configuration/signatures/#separate_signature )
            show_signature_annotations: true  ## show type annotations in function signatures (see: https://mkdocstrings.github.io/python/usage/configuration/signatures/#show_signature_annotations )
            # show_root_toc_entry: false  ## hide methods from TOC, you can specify them manually with the `toc_label` option (see: https://mkdocstrings.github.io/python/usage/configuration/headings/#show_root_toc_entry )


extra_css:
  - assets/css/fonts.css
  - assets/css/themes.css


## LaTeX, MathJax (see: https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml )
## Code blocks (see: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/ )
## Admonitions (see: https://squidfunk.github.io/mkdocs-material/reference/admonitions/ )
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list  ## allow HTML attributes in markdown, e.g. open links in new tabs by appending `{target="_blank"}` (see: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists )
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js





## Site map
nav:
  - Home: index.md

  - Usage:
    - content/usage/index.md

    - Getting Started:
      - Installation: content/usage/getting_started/installation.md
      # - Datasets: content/usage/getting_started/datasets.md
      # - Analysis: content/usage/getting_started/analysis.md

    - API Reference:
      - content/usage/api/index.md
      - Crust:
        - Bouguer Anomaly:
          - load()         : content/usage/api/crust/boug/load.md
          - get()          : content/usage/api/crust/boug/get.md
          - get_metadata() : content/usage/api/crust/boug/get_metadata.md
          - get_dataset()  : content/usage/api/crust/boug/get_dataset.md


  - Supplemental:
    - content/supplemental/index.md

    # - Datasets:
    #   - Crust:
    #     - Bouguer Anomaly: content/supplemental/datasets/crust/boug.md
    - Impact Demagnetization: content/supplemental/impact_demagnetization.md
    - Radial Profile: content/supplemental/radial_profile.md
    - Plotting: content/supplemental/plotting.md
    # - Heat Flow: content/supplemental/heat_flow.md


  - About:
    - Contact: content/about/contact.md
    - Changelog: content/about/changelog.md
    - License: content/about/license.md
    - Contributing: content/about/contributing.md
