name: Continuous Integration



on:
  push:
    branches-ignore:
      - gh-pages



jobs:


  test:

    strategy:
      fail-fast: false  ## continue running jobs even if one fails
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      ## uv guide: https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v5
        with:
          # version: "0.6.4"  ## specific version of uv (good practice for reproducibility, but I'm worried I'll forget to update)
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: uv sync --dev  ## leave out `-all-extras` for now -- in the future, add back "interactive" group if I add plotting tests

      - name: Run tests with pytest
        run: uv run pytest tests
